typescript/libs配下に汎用関数/型群を定義し、adminで利用できるように
ispec-inc/monorepo pull request #380
Opened 2021-09-29 04:56 UTC by minminzemi

## 該当イシュー
なし

## 外部仕様の変更点
(フロントエンド の人に説明する必要がある場合)

## 内部仕様の変更点
- SSIA
  - nullを含む配列から、nullを除外した配列を返す`filterNull()`
  - 渡された値がnullかundefinedならtrue、そうでなければfalseを返す`isNullOrUndefined()`
  - オブジェクト、配列などのディープコピーを行える`rfdcClone()`([rfdc](https://github.com/davidmarkclements/rfdc)を利用)
  - `ある型T or null`を表す型`Maybe<T>`
  - Promise<T>のTの部分を取得する型`UnpackPromise<T>`
    - `UnpackPromise<Promise<number>> // -> number`
- 汎用関数群のテストの追加
  - PR作成時に自動でテストが走るように

## 動作を保証するためのテストケースの詳細
- rspecのテストケース
- エンドツーエンドテストケース

## 備考
utils-function

2021-11-01 03:18 UTC, kouhaa reviewed
@minminzemi 
お疲れ様です！

いくつかコメントさせていただいたので、確認をお願いいたします！
テスト周りについてはまた別途レビューさせていただきます！

2021-11-01 03:18 UTC, kouhaa commented on typescript/libs/util-functions/package.json
> +    "update": "tsc && rm -rf node_modules && yarn workspace @monorepo/admin install",
それと、tsc って package 作成する都合上必要なんでしたっけ？

一応試してみたんですけど、lib自体が、typescriptで書かれているので、appsの方はほぼほぼ確実にtypescript使っている現状で直接 `util/general-function/src` からもimportはできそうな雰囲気はありました。

`util-functions/dist/` 配下にアクセスするにも、tscコマンドの実行が必要そうですかね？
`yarn add` だけでうまく使えるようにできたらいいなとは思いました。

2021-11-01 03:18 UTC, kouhaa commented on typescript/apps/admin/package.json
> +    "@monorepo/utils-functions": "./libs/util-functions",
libの名前と指定の名前が異なるので、インポートが変な感じになってしまってました。

```
"@monorepo/util-functions": "./libs/util-functions"
```
とするのがいいかなと思ったのですが、packageは直接書き換えた感じですかね？

2021-11-01 07:32 UTC, minminzemi commented on typescript/libs/util-functions/package.json
> +    "update": "tsc && rm -rf node_modules && yarn workspace @monorepo/admin install",
package

2021-11-01 07:36 UTC, minminzemi commented on typescript/libs/util-functions/package.json
> +    "update": "tsc && rm -rf node_modules && yarn workspace @monorepo/admin install",
あ、ここで定義しているコマンドは、ライブラリ利用側で使うものではなく、ライブラリのコードを更新した後に行っておく必要のあるコマンドをまとめただけのものなので、`yarn upgrade`とは意味合いが違うものになります:bow:

fast-formで、コードを更新した後にコンパイルしてadmin側でinstallしても更新後のライブラリが読み込まれない不具合があり、その際に`typescript/node_modules`を一度削除する必要があることがわかったので、この`util-functions`でも同様にするためにこのコマンドを定義しました

tscはtypescriptを用いたパッケージ開発では必要になるものだと思います
typescriptを用いたnpmパッケージの開発について軽く調べてみましたが、コンパイル後のものをexportしていたので

2021-11-01 07:45 UTC, minminzemi commented on typescript/apps/admin/package.json
> +    "@monorepo/utils-functions": "./libs/util-functions",
こちら修正しました！

2021-11-02 12:37 UTC, kouhaa requested changes
いろいろ調べていただいてありがとうございました！
僕の方も納得できました！

テストの部分だけ追加で確認したので、そこだけ修正をお願いできると嬉しいですQ!

2021-11-02 12:37 UTC, kouhaa commented on typescript/libs/util-functions/package.json
> +    "update": "tsc && rm -rf node_modules && yarn workspace @monorepo/admin install",
なるほど理解しました！

そしたら、libの更新後はyarnが検知できないから、node_moduleを消してもう一度入れ直す必要があるんですね。
ローカルでやる以上仕方なさそうなので、これで大丈夫そうです！

2021-11-02 12:37 UTC, kouhaa commented on typescript/libs/util-functions/package.json
> +    "update": "tsc && rm -rf node_modules && yarn workspace @monorepo/admin install",
コンパイルについてもありがとうございます！

そこらのパッケージみんなコンパイルされてるんですね。
と言うことは、monorepoではコンパイルされた `/dist/`ごとgit管理するって形になる想定ですかね？

パッケージ開発いろいろ知らなきゃ行けなさそうなことがありそうですね。僕も精進します。
ありがとうございます！

2021-11-02 12:37 UTC, kouhaa commented on typescript/libs/util-functions/jest.config.ts
> +  collectCoverageFrom: ['**/*.{ts}', '!**/node_modules/**'],
テストの作成までありがとうございました！
packageごとにjest入れれば、今まで通りにテストができますね！

動いているところも確認できました。

あとは、ここの`collectCoverageFromの値が今書いてあるものだとうまく認識しないみたいで、全て0%扱いになってしまっているみたいです。

ここはundefinedのままでもうまく集計してくれているので、消しちゃって大丈夫そうです！

2021-11-04 05:53 UTC, minminzemi commented
確認ありがとうございます！

> monorepoではコンパイルされた /dist/ごとgit管理するって形になる想定ですかね？

util-functionsは、すでにlibsでパッケージ化されていたfast-formに倣って作成していて、こちらもdistまでgitで管理しているようでしたので、その想定になります！

`collectCoverageFrom`の設定も外しておきました！再度確認よろしくお願いします:pray:

2021-11-05 07:56 UTC, kouhaa reviewed
![LGTM](https://image.lgtmoon.dev/144802)

2021-11-05 07:56 UTC, kouhaa commented
@minminzemi 
ありがとうございました！

いい感じです！

2021-11-05 08:11 UTC, merged